### PR TITLE
RAM_Toolkit: Refactoring to individual method files

### LINKED ISSUE #192: Refactor CRUD
#### Broken rules:

All the CRUDS are in single files for C, R, U, and D.

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #192

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot fix project file ref. 4359083764

**Comment by JosefTaylor** [comment]
@BHoMBot check project-compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot fix project file ref. 4374325700

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Review by enarhi — APPROVED** [review]
LGTM, test script works as expected although it is only testing creation. @JosefTaylor do we need to test read as well or do these changes only effect RAM Creation?

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
