### PR TITLE
RAM_Toolkit: Code Cleanup

### LINKED ISSUE #60: RAM_Toolkit : Making ToBHoM methods extension methods where possible
As discussed with @IsakNaslundBh useful to add `this` keyword to the first argument in your conversion methods

### LINKED ISSUE #61: RAM_Toolkit : Migrate methods making COM calls from Engine to Adapter
The Engine Convert namespace should be reserved for conversion between object representations only.
The explicit calling of the API COM calls should be made by the Adapter itself.

### LINKED ISSUE #63: RAM_Toolkit : Remove (provide comment block for) all commented out code
As discussed - you can easily restore any old code - include commented out code - from previous commits in Git. Therefore keeping commented out code should be avoided.

Possibility of keeping small blocks for some short testing purposes obviously.
Worth adding a comment block to explain reasoning to help others (our future selves!)

### LINKED ISSUE #64: RAM : Review RAM_Test_1 Project
Candidate for possible deletion and recreation (maybe)

### LINKED ISSUE #65: RAM_Toolkit : Delete NextId.cs

### LINKED ISSUE #66: RAM_Toolkit : Delete Create/Read Node Collection methods
As these are not possible in RAM

### PR DESCRIPTION
**Pull request by enarhi**
Closes #60 
Closes #61 
Closes #63 
Closes #64 
Closes #65 
Closes #66 

Code cleanup. Cleaned and deleted comments as necessary; removed unused code for NextId, Nodes, and test (proper testing planned in future release); convert methods are now extension methods.

### CODE REVIEW

**Comment by enarhi** [comment]
Test scripts for read and create below

[Read](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/RAM_Toolkit/BHoM%20Test%20Script%20-%20Read%20-%20RAM.gh?csf=1&e=V3iluw)

[Create](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/RAM_Toolkit/BHoM%20Test%20Script%20-%20Create%20-%20RAM.gh?csf=1&e=9dmzXR)

**Comment by JosefTaylor** [comment]
I've got some bad sloping behavior out of the roof in the create example. Horizontal purlins are at the right elevation, however the sloped rafters are not sloped correctly. Columns do not make it to the sloped roof, stopping at the floor below.

**Comment by enarhi** [comment]
@JosefTaylor that is expected behavior at this point, future feature to be added is support for slopes. Going to wrap that into level handling as part of the upcoming refactoring, where each object's creation will call a method that returns object's level, making incorporation of level offsets (and therefore slopes) easier as a result.

**Comment by JosefTaylor** [comment]
Hanging columns come in as standard columns, need to be duplicated on floor below as hanging columns.

**Comment by JosefTaylor** [comment]
Floors don't seem to come in at all

**Comment by enarhi** [comment]
Last commit fixes misspelling and separators.

**Pull request merged**
