### PR TITLE
Improve error handling in ReadPanel()

### LINKED ISSUE #195: RAM fails to pull all floors if any floors error

### PR DESCRIPTION
**Pull request by JosefTaylor**
### Issues addressed by this PR

Closes #195 

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/RAM_Toolkit/%23196-fix-panel-pull/BuroHappold_BHoM_v5.0.beta_Create%20-%20read%20-%20update%20elements%20-%20building.gh?csf=1&web=1&e=CsS8Wd

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check installer

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Review by mchaf — APPROVED** [review]
LGTM

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
