### PR TITLE
Ram_Toolkit: Floor creation handling with slab edges and section assignments for bars

### LINKED ISSUE #19: RAM_Toolkit: Floor Create Functionality
Add floor create functionality with openings.

### PR DESCRIPTION
**Pull request by enarhi**
Fixes #19. Floors are now created as slab edges allowing quick addition of decks per floor as applicable. Beams and columns come in with correct section applied, and analyze enum set to analyze to enforce analysis of imported sizes. Selection of members to optimize can then be done through RAM starting with like for like sizes per pushed objects.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@JosefTaylor and @enarhi How are things progressing here? Are you able to test and review this PR or do you need some more support?

**Comment by enarhi** [comment]
@IsakNaslundBh we are all set, should have this one reviewed by early next week.

**Comment by JosefTaylor** [comment]
I'm having negative floor elevation errors, in spite of ensuring everything is zero or positive.

**Comment by enarhi** [comment]
@JosefTaylor can you check with levels above zero only (no level at 0 exactly) and confirm if this works please?

**Pull request merged**
