### PR TITLE
Area loads working, database opening and closing glitching fixed

### LINKED ISSUE #51: RAM_Toolkit: Read, toggle, read again causes freeze
image
Freezes when active is toggled for a second time to read a model file.

### LINKED ISSUE #91: RAM_Toolkit: Create functionality for area loads
Add features for load creation.

### LINKED ISSUE #107: RAM_Toolkit: Resolve warnings
**By 30th November please**

#### Broken rules:
Compiler warnings occur when compiling the toolkit.

#### Suggestions to restore compliance:
Ensure code compiles without any warnings.

### PR DESCRIPTION
**Pull request by enarhi**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/151

### Issues addressed by this PR

Closes #91 (fully)
Closes #51 
Closes #107

### Changelog

- Added support for reading and creating area loads
- Fixed Read/Toggle/Read glitch caused by API calls and database handling

### CODE REVIEW

**Comment by JosefTaylor** [comment]
Added open/close database in the push/pull override. @enarhi back to you!

**Comment by enarhi** [comment]
This one is ready to go. @JosefTaylor please review with my latest commits to ensure full functionality with new database handling. Updated test script to test model read/create roundtripping at:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/RAM_Toolkit/Issue91%20Area%20Loads?csf=1&e=UfT5Tu

**Comment by JosefTaylor** [comment]
Looks like read ContourLoadSet is failing, which can cause the pull to fail, and that causes the database not to close.

**Comment by JosefTaylor** [comment]
Wrapping the pull/push keeps the wheels on, however pull ContourLoadSet still fails.

**Comment by JosefTaylor** [comment]
This should do it @enarhi, tested with my models.

**Pull request merged**
